dx: halt loudly when part of a tooling script fails
By default, bash continues running in the face of most errors, which
means that step two will start even though step one failed.

This patch introduces a "strict mode" arrangement, which means that the
script will halt if any line fails unexpectedly. This makes it more
obvious where a problem is occuring.

diff --git a/tools/start-appium-server b/tools/start-appium-server
--- a/tools/start-appium-server
+++ b/tools/start-appium-server
@@ -1,3 +1,12 @@
 #!/bin/bash
+set -eEu -o pipefail
+shopt -s extdebug
+IFS=$'\n\t'
+trap 'onFailure $?' ERR
+
+function onFailure() {
+  echo "Unhandled script error $1 at ${BASH_SOURCE[0]}:${BASH_LINENO[0]}" >&2
+  exit 1
+}
 
 $(npm bin)/appium --port 4995 > appium.log & echo $! > appium-server.pid
diff --git a/tools/stop-appium-server b/tools/stop-appium-server
--- a/tools/stop-appium-server
+++ b/tools/stop-appium-server
@@ -1,4 +1,13 @@
 #!/bin/bash
+set -eEu -o pipefail
+shopt -s extdebug
+IFS=$'\n\t'
+trap 'onFailure $?' ERR
+
+function onFailure() {
+  echo "Unhandled script error $1 at ${BASH_SOURCE[0]}:${BASH_LINENO[0]}" >&2
+  exit 1
+}
 
 if ps -p $(cat appium-server.pid)> /dev/null; then
   kill -KILL $(cat appium-server.pid);
